title: Tan Kai Min, Russell
description: Back-up site
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  "Main Site" : 
    - "https://www.russelltankm.com"

footer_content: Copyright &copy;russelltankaimin. All contents and information are updated as on 07/05/2024.
